create table address (id uuid not null, city varchar(255), country varchar(255), state varchar(255), street_address1 varchar(255), street_address2 varchar(255), zipcode varchar(255), primary key (id));
create table appointment_product_services (appointment_id uuid not null, item_id uuid not null);
create table appointment_purchases (appointment_id uuid not null, item_id uuid not null);
create table appointments (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), appointment_date date, appointment_time time, cancellation_from varchar(255), cancellation_reason varchar(255), customer_feedback varchar(255), end_time time, expected_end_time time, expected_start_time time, notes text, rescheduled_by varchar(255), start_time time, status int4, assigned_to uuid, branch_id uuid, customer_id uuid, invoice_id uuid, rescheduled_with uuid, primary key (id));
create table branches (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), contact_no varchar(255), email varchar(255), name varchar(255), status int4, address_id uuid, company_id uuid, work_schedule_id uuid, primary key (id));
create table companies (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), contact_no varchar(255), email varchar(255), name varchar(255), status int4, address_id uuid, primary key (id));
create table coupons (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), end_date timestamp, max_redemptions int4, name varchar(255), start_date timestamp, status int4, type int4, value float4, primary key (id));
create table customers (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), avatar varchar(255), email varchar(255), federation int4, first_name varchar(255), gender int4, last_name varchar(255), mobile varchar(255), status int4, username varchar(255), address_id uuid, primary key (id));
create table invoice_items (invoice_id uuid not null, item_id uuid not null);
create table invoices (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), customer_name varchar(255), discount float8, discount_str varchar(255), gross_total float8, net_total float8, posting_date date, status int4, tax_str TEXT, taxes float8, branch_id uuid, customer_user_id uuid, promotion_id uuid, primary key (id));
create table items (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), brand varchar(255), code varchar(255), cost float8, description varchar(255), item_type int4, name varchar(255), price float8, status int4, primary key (id));
create table payments (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), payment_date date, payment_ref varchar(255), payment_type int4, invoice_id uuid, primary key (id));
create table promotions (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), code varchar(255), end_date timestamp, max_redemptions int4, status int4, times_redeemed int4, coupon_id uuid, primary key (id));
create table tax_heads (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), charge_on int4, code varchar(255) not null, name varchar(255), status int4, primary key (id));
create table tax_schedule_items (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), on_value_from float4 not null, on_value_to float4 not null, tax_charge_type int4, value float4 not null, branch_id uuid, tax_head_id uuid, tax_schedule_id uuid, primary key (id));
create table tax_schedules (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), name varchar(255), status int4, branch_id uuid, primary key (id));
create table users (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), avatar varchar(255), bizio_id varchar(255), designation varchar(255), email varchar(255), emp_code varchar(255), emp_type int4, first_name varchar(255), gender int4, last_name varchar(255), mobile varchar(255), pay_schedule int4, status int4, username varchar(255), address_id uuid, branch_id uuid, work_schedule_id uuid, primary key (id));
create table work_schedule_items (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), break_end_time time, break_start_time time, day int4, end_time time, start_time time, work_schedule_id uuid, primary key (id));
create table work_schedules (id uuid not null, created_at timestamp default CURRENT_TIMESTAMP not null, created_by varchar(255), modified_at timestamp, modified_by varchar(255), name varchar(255), status int4, primary key (id));
alter table tax_heads add constraint UK_9m5bqvh319n6leu395c24m1rt unique (code);
alter table appointment_product_services add constraint FKq9rs1gwlhv2ico5rl0fyl5jo5 foreign key (item_id) references items;
alter table appointment_product_services add constraint FKjbburw1ajx82t4oruje4efdh foreign key (appointment_id) references appointments;
alter table appointment_purchases add constraint FKoxqlwc4ycw3jnlsroydpraq35 foreign key (item_id) references items;
alter table appointment_purchases add constraint FKmrvp6gcnpnxtc1et445lk41og foreign key (appointment_id) references appointments;
alter table appointments add constraint FK5ndaoxlylmlqdm2dvy3y231cn foreign key (assigned_to) references users;
alter table appointments add constraint FKk8jy62c7ppxcky9c3dvqf69k5 foreign key (branch_id) references branches;
alter table appointments add constraint FKrlbb09f329sfsmftrh7y0yxtk foreign key (customer_id) references customers;
alter table appointments add constraint FKd79mhhc42nv0ykp79e968mvfb foreign key (invoice_id) references invoices;
alter table appointments add constraint FKp3c9ridd90xyhojpi5tgwnc6a foreign key (rescheduled_with) references appointments;
alter table branches add constraint FKftwc084osodj17nmlduxqr563 foreign key (address_id) references address;
alter table branches add constraint FKjuiihymin83oadf71ou3oelya foreign key (company_id) references companies;
alter table branches add constraint FK9nttrc16fli95kt2u4spwfbxm foreign key (work_schedule_id) references work_schedules;
alter table companies add constraint FKhet647l0s0633q0sbdd67qmq4 foreign key (address_id) references address;
alter table customers add constraint FK48149pc9p9060ooav2ny1xehg foreign key (address_id) references address;
alter table invoice_items add constraint FKao8886xiq7x18lwksgxflc995 foreign key (item_id) references items;
alter table invoice_items add constraint FK46ae0lhu1oqs7cv91fn6y9n7w foreign key (invoice_id) references invoices;
alter table invoices add constraint FK2m7cj392b6vvvhw3ka3fknofh foreign key (branch_id) references branches;
alter table invoices add constraint FKi15981adwvpubx394j6fodfwm foreign key (customer_user_id) references customers;
alter table invoices add constraint FKsev3d3jlk86toj8l50myia2ts foreign key (promotion_id) references promotions;
alter table payments add constraint FKrbqec6be74wab8iifh8g3i50i foreign key (invoice_id) references invoices;
alter table promotions add constraint FKsukt3svg0ykmb1yrpp6jn6pik foreign key (coupon_id) references coupons;
alter table tax_schedule_items add constraint FK55sb3p3c96swja0kt18wadf9e foreign key (branch_id) references branches;
alter table tax_schedule_items add constraint FK3co5k7usg4bhpj9ep82di6afw foreign key (tax_head_id) references tax_heads;
alter table tax_schedule_items add constraint FKb45cba7k5svowd5wdwdxdrahv foreign key (tax_schedule_id) references tax_schedules;
alter table tax_schedules add constraint FK3h5o7u8xwueh4449xtwdhru31 foreign key (branch_id) references branches;
alter table users add constraint FKditu6lr4ek16tkxtdsne0gxib foreign key (address_id) references address;
alter table users add constraint FK9o70sp9ku40077y38fk4wieyk foreign key (branch_id) references branches;
alter table users add constraint FK104a1h92gfbeapurgl8gelld1 foreign key (work_schedule_id) references work_schedules;
alter table work_schedule_items add constraint FKsrxj2nplmoenh6ui2x2c91jgp foreign key (work_schedule_id) references work_schedules;
